# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73da0bb6a214f4c213b416a5ad79c1af956f1e25b6ff04de07aeb08de3a1023c63f3f9fd059f41e01b4753bc8f07739a6e341916f2b6733e3e9c39d913999f7d

test:
  secret_key_base: 29db6d7ca978be97eed3b9219ef7cd5d6508b6fabf73ea9eae4a4759b0084ee1a7e6bf64da052dec77f24db7cce4c71eddd80b325b3fa2487a83d65e9449ddb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
